services:
  api-bixi:
    build: ./api/
    container_name: apibixi
    ports:
      - 3002:3002

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometeus/prometeus-config.yml:/etc/prometheus/prometheus-config.yml
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

volumes:
  grafana-data:
    external: true