name: chaos-test-lab1
services:
  api-bixi:
    build: ./api/
    container_name: apibixi
    environment:
      JAEGER_URI: ${JAEG_URI}
    ports:
      - 3002:3002
    depends_on:
      - loki
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometeus/prometeus-config.yml:/etc/prometheus/prometheus-config.yml
      - ./prometeus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports: 
      - '9093:9003'
    volumes:
      - ./prometeus/alertmanager.yml:/config/alertmanager.yml
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml
    depends_on:
      - prometheus

  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USR}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PSWD}
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  loki:
    image: grafana/loki:main
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # UDP port for Jaeger agent
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      
volumes:
  grafana-data:
    external: true
  alertmanager-data: