{
 "title": "latency Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Gateway",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_gateway_response_time_duration_seconds_sum{app=\"node-api-gateway\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"node-apigateway\"} |= ``"
    }
   ]
  },
  {
   "title": "API Bixi Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "{service_name=\"node-bixi\"} |= ``"
    }
   ]
  }
 ]
}